# Generated by Django 5.2.15 on 2026-06-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="country",
            field=models.CharField(default="Germany", max_length=100),
        ),
    ]
