# Generated by Django 5.2.15 on 2026-06-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_customerprofile_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customerprofile",
            name="national_id_number",
            field=models.CharField(
                blank=True, max_length=30, verbose_name="Tax ID / National ID"
            ),
        ),
    ]
