# Generated by Django 5.2.15 on 2026-06-13 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("banking", "0002_alter_transaction_counterparty_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StandingOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("beneficiary_name", models.CharField(max_length=150)),
                (
                    "destination_iban",
                    models.CharField(max_length=34, verbose_name="Beneficiary IBAN"),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=14)),
                ("narration", models.CharField(blank=True, max_length=140)),
                (
                    "frequency",
                    models.CharField(
                        choices=[
                            ("WEEKLY", "Weekly"),
                            ("FORTNIGHTLY", "Every two weeks"),
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Every three months"),
                            ("YEARLY", "Yearly"),
                        ],
                        max_length=12,
                    ),
                ),
                ("start_date", models.DateField()),
                ("next_run_date", models.DateField(db_index=True)),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional. Leave blank to run until cancelled or the run cap is reached.",
                        null=True,
                    ),
                ),
                (
                    "max_executions",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Optional. Stop automatically after this many payments.",
                        null=True,
                    ),
                ),
                ("executions_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Active"),
                            ("PAUSED", "Paused"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ACTIVE",
                        max_length=10,
                    ),
                ),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="standing_orders",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="standing_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["next_run_date", "-created_at"],
            },
        ),
    ]
