# Generated by Django 5.2.15 on 2026-06-12 18:28

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("banking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Card",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("VERVE", "Verve"),
                            ("VISA", "Visa"),
                            ("MASTERCARD", "Mastercard"),
                        ],
                        max_length=12,
                    ),
                ),
                (
                    "card_number",
                    models.CharField(blank=True, max_length=16, unique=True),
                ),
                ("cvv", models.CharField(blank=True, max_length=3)),
                (
                    "expiry_month",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "expiry_year",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "Requested"),
                            ("ACTIVE", "Active"),
                            ("FROZEN", "Frozen"),
                            ("BLOCKED", "Blocked"),
                            ("EXPIRED", "Expired"),
                        ],
                        default="REQUESTED",
                        max_length=10,
                    ),
                ),
                (
                    "daily_spend_limit",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("500000.00"), max_digits=12
                    ),
                ),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="banking.bankaccount",
                    ),
                ),
                (
                    "issued_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
            },
        ),
    ]
