# Generated by Django 5.2.15 on 2026-06-13 05:46

from django.db import migrations, models


def migrate_verve_to_girocard(apps, schema_editor):
    Card = apps.get_model("cards", "Card")
    Card.objects.filter(scheme="VERVE").update(scheme="GIROCARD")


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(migrate_verve_to_girocard, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="card",
            name="scheme",
            field=models.CharField(
                choices=[
                    ("GIROCARD", "Girocard"),
                    ("VISA", "Visa"),
                    ("MASTERCARD", "Mastercard"),
                ],
                max_length=12,
            ),
        ),
    ]
